[skip ci] - debug test for issue https://github.com/abcdesktopio/board/issues/3

diff --git a/charts/abcdesktop/templates/jwtdesktoppayload-secretgenerator-job.yaml b/charts/abcdesktop/templates/jwtdesktoppayload-secretgenerator-job.yaml
--- a/charts/abcdesktop/templates/jwtdesktoppayload-secretgenerator-job.yaml
+++ b/charts/abcdesktop/templates/jwtdesktoppayload-secretgenerator-job.yaml
@@ -3,6 +3,9 @@ kind: Job
 metadata:
   namespace: {{ .Release.Namespace }}
   name: generate-jwtdesktoppayload-keys
+  # annotations:
+  #   "helm.sh/hook": post-install,post-upgrade
+  #   "helm.sh/hook-weight": "5"
 spec:
   template:
     spec:
@@ -23,9 +26,14 @@ spec:
             openssl rsa -in abcdesktop_jwt_desktop_payload_private_key.pem -outform PEM -pubout -out  _abcdesktop_jwt_desktop_payload_public_key.pem && \
             openssl rsa -pubin -in _abcdesktop_jwt_desktop_payload_public_key.pem -RSAPublicKey_out -out abcdesktop_jwt_desktop_payload_public_key.pem && \
             if ! kubectl get secret abcdesktopjwtdesktoppayload --namespace={{ .Release.Namespace }} >/dev/null 2>&1; then
-              kubectl create secret generic abcdesktopjwtdesktoppayload --from-file=abcdesktop_jwt_desktop_payload_private_key.pem --from-file=abcdesktop_jwt_desktop_payload_public_key.pem --namespace={{ .Release.Namespace }}
+              if ! kubectl create secret generic abcdesktopjwtdesktoppayload --from-file=abcdesktop_jwt_desktop_payload_private_key.pem --from-file=abcdesktop_jwt_desktop_payload_public_key.pem --namespace={{ .Release.Namespace }};
+              then
+                echo "Failed to create secret"
+                exit 1
+              fi
             else
               echo "Secret already exists"
+              exit 0
             fi
       {{- with .Values.nodeSelector }}
       nodeSelector:
diff --git a/charts/abcdesktop/templates/jwtdesktopsigning-secretgenerator-job.yaml b/charts/abcdesktop/templates/jwtdesktopsigning-secretgenerator-job.yaml
--- a/charts/abcdesktop/templates/jwtdesktopsigning-secretgenerator-job.yaml
+++ b/charts/abcdesktop/templates/jwtdesktopsigning-secretgenerator-job.yaml
@@ -3,6 +3,9 @@ kind: Job
 metadata:
   namespace: {{ .Release.Namespace }}
   name: generate-jwtdesktopsigning-keys
+  # annotations:
+  #   "helm.sh/hook": post-install,post-upgrade
+  #   "helm.sh/hook-weight": "5"
 spec:
   template:
     spec:
@@ -22,9 +25,14 @@ spec:
             openssl genrsa -out abcdesktop_jwt_desktop_signing_private_key.pem {{ .Values.keysgenerator.jwtdesktopsigningkeylength }}  && \
             openssl rsa -in abcdesktop_jwt_desktop_signing_private_key.pem -outform PEM -pubout -out abcdesktop_jwt_desktop_signing_public_key.pem && \
             if ! kubectl get secret abcdesktopjwtdesktopsigning --namespace={{ .Release.Namespace }} >/dev/null 2>&1; then
-              kubectl create secret generic abcdesktopjwtdesktopsigning --from-file=abcdesktop_jwt_desktop_signing_private_key.pem --from-file=abcdesktop_jwt_desktop_signing_public_key.pem --namespace={{ .Release.Namespace }}
+              if kubectl create secret generic abcdesktopjwtdesktopsigning --from-file=abcdesktop_jwt_desktop_signing_private_key.pem --from-file=abcdesktop_jwt_desktop_signing_public_key.pem --namespace={{ .Release.Namespace }};
+              then
+                echo "Failed to create secret"
+                exit 1
+              fi
             else
               echo "Secret already exists"
+              exit 0
             fi
       {{- with .Values.nodeSelector }}
       nodeSelector:
